Guard against redefinition of cmake targets
If a find_package(libaec) call is invoked twice, the second one will fail with

CMake Error at /usr/lib/cmake/libaec/libaec-config.cmake:52 (add_library):
  add_library cannot create ALIAS target "libaec::aec" because another target
  with the same name already exists.

This breaks gdal build against hdf5 2.0, where libaec is included twice: once directly and once via hdf5.